### ISSUE TITLE
Invisible chapters

### ISSUE THREAD

**Issue by bentley** [standardebooks/ulysses-s-grant_personal-memoirs-of-ulysses-s-grant#6]
On my Kindle Voyage, the first page (and only the first page) of each of the following chapters is blank. The chapter heading and bridgehead are invisible. The first paragraphs of actual text begin on the next page.

* Chapter 27
* Chapter 38
* Chapter 57
* Chapter 63

I see this on 8e85a1d, but also saw it in earlier revisions.

**Comment by acabal** [comment]
Hard to say why that would be. It's almost certainly a Kindle rendering error. Their ebook renderer is very poor. 

This book is especially complex and hard to render because of the large maps and figures. Could be that the renderer is choking on one of those earlier down the line, maybe running out of memory before reaching a particular chapter. Who knows. :(
